//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false, ElementName= "root")]
public partial class Holiday {
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string emailField;
    
    private string phoneField;
    
    private string holidayTypeField;
    
    private string holidayCountryField;
    
    private string holidayDateField;
    
    private string commentsField;
    
    public Holiday() {
        this.holidayCountryField = "af";
    }
    
    /// <remarks/>
    public string FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string LastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public string HolidayType {
        get {
            return this.holidayTypeField;
        }
        set {
            this.holidayTypeField = value;
        }
    }
    
    /// <remarks/>
    public string HolidayCountry {
        get {
            return this.holidayCountryField;
        }
        set {
            this.holidayCountryField = value;
        }
    }
    
    /// <remarks/>
    public string HolidayDate {
        get {
            return this.holidayDateField;
        }
        set {
            this.holidayDateField = value;
        }
    }
    
    /// <remarks/>
    public string Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
}
