//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace NewDevTraining {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false, ElementName = "root")]
    public partial class Carousel {
        
        private rootCarouselItem[] carouselItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CarouselItem")]
        public rootCarouselItem[] CarouselItem {
            get {
                return this.carouselItemField;
            }
            set {
                this.carouselItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class rootCarouselItem {
        
        private string iconField;
        
        private string smallImageField;
        
        private string largeImageField;
        
        private string image724Field;
        
        private string image940Field;
        
        private string linkField;
        
        /// <remarks/>
        public string Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public string SmallImage {
            get {
                return this.smallImageField;
            }
            set {
                this.smallImageField = value;
            }
        }
        
        /// <remarks/>
        public string LargeImage {
            get {
                return this.largeImageField;
            }
            set {
                this.largeImageField = value;
            }
        }
        
        /// <remarks/>
        public string Image724 {
            get {
                return this.image724Field;
            }
            set {
                this.image724Field = value;
            }
        }
        
        /// <remarks/>
        public string Image940 {
            get {
                return this.image940Field;
            }
            set {
                this.image940Field = value;
            }
        }
        
        /// <remarks/>
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
    }
}
